# /Users/d.lutscher/.config/tmuxinator/autocomp-ds-repl.yml

name: autocomp-ds-repl
root: ~/

# Optional tmux socket
socket_name: default

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
on_project_start: cf ~/Documents/projects/dh-cc-automations-ds

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - editor:
      layout: e61e,158x47,0,0[158x30,0,0,5,158x16,0,31{79x16,0,31,6,78x16,80,31,7}]
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - ide:
          - cd Documents/projects/dh-cc-automations-ds && poetry shell && nvim .
        - repl:
          - cd Documents/projects/dh-cc-automations-ds && poetry run ipython
        - zsh:
          - cd ~/Documents/projects/dh-cc-automations-ds
